# Generated by ChatGPT on 2026-02-04

from django.db import migrations, models

ROLE_CHOICES = [
    ('admin', 'Administrator'),
    ('manager', 'Manager'),
    ('supervisor', 'Supervisor'),
    ('employee', 'Employee'),
    ('intern', 'Intern'),
]

PERMISSION_CHOICES = [
    ('view_attendance', 'View Attendance'),
    ('edit_attendance', 'Edit Attendance'),
    ('view_payroll', 'View Payroll'),
    ('edit_payroll', 'Edit Payroll'),
    ('view_employees', 'View Employees'),
    ('edit_employees', 'Edit Employees'),
    ('view_reports', 'View Reports'),
    ('manage_roles', 'Manage Roles'),
    ('manage_permissions', 'Manage Permissions'),
]


def forwards_copy_role_permissions(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Role = apps.get_model('accounts', 'Role')
    Permission = apps.get_model('accounts', 'Permission')

    role_map = {role.id: role.name for role in Role.objects.all()}
    perm_map = {perm.id: perm.name for perm in Permission.objects.all()}

    for user in CustomUser.objects.all().iterator():
        role_code = role_map.get(user.role_id) if user.role_id else None
        permissions_list = [
            perm_map.get(perm_id)
            for perm_id in user.permissions.values_list('id', flat=True)
            if perm_map.get(perm_id)
        ]
        user.role_code = role_code
        user.permissions_list = permissions_list
        user.save(update_fields=['role_code', 'permissions_list'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_code',
            field=models.CharField(blank=True, choices=ROLE_CHOICES, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permissions_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(forwards_copy_role_permissions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='role_code',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='permissions_list',
            new_name='permissions',
        ),
    ]
