# Generated by Django 5.0.4 on 2026-02-26 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_accounts_cu_departm_38d9c8_idx_and_more'),
        ('todos', '0002_todonotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='departmenttask',
            index=models.Index(fields=['department', 'status'], name='todos_depar_departm_671811_idx'),
        ),
        migrations.AddIndex(
            model_name='departmenttask',
            index=models.Index(fields=['deleted_at'], name='todos_depar_deleted_c832d0_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'todo_type'], name='todos_todo_user_id_cddd61_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['group', 'is_confirmed'], name='todos_todo_group_i_5f200e_idx'),
        ),
        migrations.AddIndex(
            model_name='todonotification',
            index=models.Index(fields=['recipient', 'is_read'], name='todos_todon_recipie_f6836a_idx'),
        ),
    ]
