# Generated by Django 5.0.4 on 2026-04-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_requests', '0007_project_materialrequest_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='accounting_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='accounting_status',
            field=models.CharField(choices=[('pending_funds', 'Pending Funds'), ('funds_released', 'Funds Released')], default='pending_funds', max_length=20),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='fund_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
