# Generated by Django 5.0.4 on 2026-04-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_requests', '0008_materialrequest_accounting_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='accounting_receipt',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
