# Generated by Django 6.0.1 on 2026-02-26 02:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('job_position', models.CharField(blank=True, max_length=255)),
                ('date_completed', models.DateField(default=django.utils.timezone.localdate)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('anticipated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('explanation', models.TextField()),
                ('employee_signature', models.URLField(blank=True, max_length=1000, null=True)),
                ('supervisor_signature', models.TextField(blank=True, null=True)),
                ('management_signature', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('periods', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
