# Generated by Django 5.0.4 on 2026-06-24 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_add_actual_hours_to_overtimerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='announcement_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='announcement_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='announcement_type',
            field=models.CharField(choices=[('all_day', 'All Day'), ('custom', 'Custom Duration'), ('indefinite', 'Indefinite')], default='all_day', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['recurrence_group'], name='cal_rec_grp_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['is_dismissed', 'announcement_type', 'date'], name='cal_ann_active_idx'),
        ),
    ]
