# Generated by Django 5.0.4 on 2026-06-25 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_calendarevent_announcement_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='visible_to_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of roles that can see this event. Empty means all roles.'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='visible_to_users',
            field=models.ManyToManyField(blank=True, help_text='Specific users who can see this event.', related_name='visible_calendar_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
