# Generated by Django 5.0.4 on 2026-06-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_calendarevent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
