# Generated by Django 5.0.4 on 2026-06-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payslip_image_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='wage_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], default='monthly', max_length=20),
        ),
    ]
